[NEW] Sport Association Module
nachoserra-domatix/cursoaeodoo2024 pull request #28
Opened 2024-02-27 14:24 UTC by FranRM

2024-02-27 14:24 UTC, FranRM commented
Added module

2024-03-11 16:26 UTC, nachoserra-domatix commented on sport_association_francisco/models/sport_match.py
> +            winner_team = rec.match_line_ids.search([('match_id','=',rec.id)], order='total_score desc', limit=1).team_id
Lo malo es que se está llamando al search teniendo ya el rec, por lo que se está haciendo otra búsqueda en todo Odoo cuando en principio ya tienes las lineas de ese partido en rec.match_line_ids

2024-03-13 17:01 UTC, FranRM commented on sport_association_francisco/models/sport_match.py
> +            winner_team = rec.match_line_ids.search([('match_id','=',rec.id)], order='total_score desc', limit=1).team_id
Corregido en commit [11a7f91]

2024-03-14 14:45 UTC, nachoserra-domatix requested changes

2024-03-14 14:45 UTC, nachoserra-domatix commented on sport_association_francisco/__manifest__.py
> +        "base","web"
como web ya hereda de base, con poner web ya estaría perfect

2024-03-14 14:45 UTC, nachoserra-domatix commented on sport_association_francisco/wizard/check_all_issues.py
> +        if self.date:
Sería si no hay fecha ¿no? y que actualizara los que tienen la fecha vacía

2024-03-20 17:02 UTC, nachoserra-domatix approved these changes

2025-08-25 10:08 UTC, closed without merging